import { useState, useEffect, Suspense } from "react";
import { useRouter } from "next/router";

import dynamic from "next/dynamic";
import { getAllPostsPaginate } from "../api/api";
import PostSection from "@/components/home-components/PostSection";
import Loading from "@/components/Loading";
import VerticalAd from "@/components/ads/verticalAd";
import PostList from "@/components/home-components/PostList";
import Head from "next/head";

const Navbar = dynamic(() => import("@/components/Navbar"));
const Footer = dynamic(() => import("@/components/Footer"));
const ScrollToTop = dynamic(() =>
  import("@/components/story-components/ScrollToTop")
);

const PaginatePosts = () => {
  const router = useRouter();
  const { pageNumber } = router.query;
  const pageNumberAsNumber = parseInt(pageNumber, 10);

  const [set1, setSet1] = useState([]);
  const [set2, setSet2] = useState([]);
  const [loading, setLoading] = useState(true);
  const [totalPages, setTotalPages] = useState(0);
  const [isDesktop, setIsDesktop] = useState(false);
  const [isFixed, setIsFixed] = useState(false);

  const perPage = 30;

  useEffect(() => {
    if (pageNumberAsNumber) {
      fetchPosts(pageNumberAsNumber);
    }
  }, [pageNumber]);

  const fetchPosts = async (pageNumber) => {
    setLoading(true);
    try {
      const results = await getAllPostsPaginate(perPage, pageNumber);
      setTotalPages(JSON.stringify(results.max_pages));

      setSet1(results.results.slice(0, 15) 
    );
      setSet2(results.results.slice(15, 30));
      setLoading(false);
    } catch (error) {
      console.error("Error fetching posts:", error);
      setLoading(true);
    } finally {
      setLoading(false);
    }
  };
  //console.log(`all posts are `, sets.results);

  const handleNextPage = () => {
    if (pageNumberAsNumber < totalPages) {
      const nextPage = pageNumberAsNumber + 1;
      router.push(`/page/${nextPage}`);
    }
  };

  const handlePreviousPage = () => {
    if (pageNumberAsNumber > 1) {
      const previousPage = pageNumberAsNumber - 1;
      router.push(`/page/${previousPage}`);
    }
  };

  useEffect(() => {
    const handleScroll = () => {
      const winTop = window.scrollY;

      // const leftHeight = left ? left.scrollHeight : 0;

      let screenWidth = window.innerWidth;

      if (screenWidth > 760) {
        setIsDesktop(true);
        if (winTop > 400 && winTop <= winTop) {
          setIsFixed(true);
        } else {
          setIsFixed(false);
        }
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const popularFixed = isFixed ? "popular-fixed" : "popular-relative-story";

  const leftMargin = isFixed ? "3%" : "12%";

  return (
    <>
      <Head>
        <title>All Stories - Echelon </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />

        <meta name="description" content="" />

        <meta
          name="viewport"
          content=" initial-scale=1.0, width=device-width"
        />

        <link rel="canonical" href="https://echelon.lk" />

        {/* <!-- Facebook Meta Tags --> */}
        <meta property="og:url" content="https://echelon.lk/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Echelon Magazine" />
        <meta property="og:description" content="" />
        <meta
          property="og:image"
          content="https://testing.echelon.lk/_next/static/media/logo.c39512be.png"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:type" content="image/jpg" />

        <meta
          property="og:image"
          content="https://testing.echelon.lk/_next/static/media/logo.c39512be.png"
        />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="400" />
        <meta property="og:image:height" content="400" />

        {/* <!-- Twitter Meta Tags --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="echelon.lk" />
        <meta property="twitter:url" content="https://echelon.lk/" />
        <meta name="twitter:title" content="Echelon Magazine" />
        <meta name="twitter:description" content="" />
        <meta
          name="twitter:image"
          content="https://testing.neonmedia.lk/_next/static/media/logo.c39512be.png"
        />

        {/* <link
          rel="preload"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          as="style"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          media="print"
          onload="this.media='all'"
        /> */}
      </Head>
      <Navbar />
      <br></br>
      {/* {currentSet && <PostSection posts={sets} />} */}
      {loading ? (
        <Loading />
      ) : (
        <>
          <main id="main" className=" lg:max-w-screen-xl">
            <div className="paginationpage ">
              <PostSection homePagePosts={set1} />
            </div>

            <div className="desktop-right-side sm-fulls">
              <div
                className={`postList ${popularFixed} `}
                style={
                  isDesktop
                    ? { marginTop: "9.5vh", marginLeft: leftMargin }
                    : { margin: " 15% 2%" }
                }
              >
                <div className="list-header bg-black h-10 ">
                  <h2 className=" text-xl text-white home-popular-header ">
                    Most Popular
                  </h2>
                  <div className="hr" />
                </div>
                <PostList />
              </div>
            </div>
          </main>
          <main id="main" className="max-w-screen-md  lg:max-w-screen-xl">
            <div className="paginationpage ">
              <PostSection homePagePosts={set2} />
            </div>
          </main>
        </>
      )}

      <div className="pagination-bar items-center   flex justify-between">
        {" "}
        {/* Flexbox for horizontal alignment */}
        {pageNumberAsNumber !== 1 && (
          <div className="pagination-previous-button">
            <button
              onClick={handlePreviousPage}
              className="text-gray-500 hover:text-gray-700"
            >
              Previous
            </button>
          </div>
        )}
        <div className="pagination-page-numbers text-gray-500">
          PAGE {pageNumberAsNumber} OF {totalPages}
        </div>
        <div className="pagination-next-button">
          <button
            onClick={handleNextPage}
            className="text-gray-500 hover:text-gray-700"
          >
            Next
          </button>
        </div>
      </div>
      <ScrollToTop />
      <Footer />
    </>
  );
};

export default PaginatePosts;
